version: '3.8'

services:
  petclinic-app:
    image: kahanhm/spring-petclinic:1.0.0
    container_name: petclinic
    ports:
      - "80:9966"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://10.10.3.5:3306/petclinicdb
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD_FILE=/run/secrets/db_password
      - SPRING_SQL_INIT_MODE=always
    secrets:
      - db_password
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  visualizer:
    image: dockersamples/visualizer:stable
    container_name: visualizer
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

secrets:
  db_password:
    external: true
