docker_edition: 'ce'
docker_packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
docker_packages_state: present

docker_install_compose_plugin: true
docker_compose_package: docker-compose-plugin
docker_compose_package_state: present

docker_service_manage: true
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted
docker_users:
    - kahan
