---
- name: Install system dependencies
  hosts: all
  become: true
  gather_facts: false
  roles:
    - role: robertdebock.bootstrap

- name: Install Docker
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - vars/docker.yml
  roles:
    - geerlingguy.docker

- name: Initialize Docker Swarm on Manager (CLI version)
  hosts: manager
  become: yes
  vars_files:
    - vars/swarm.yml
  tasks:
    - name: Check if swarm already initialized
      command: docker info --format '{{ '{{.Swarm.LocalNodeState}}' }}'
      register: swarm_status
      changed_when: false
      ignore_errors: yes

    - name: Init Swarm if not already initialized
      command: docker swarm init --advertise-addr {{ manager_ip }}
      when: swarm_status.stdout != "active" or swarm_status.rc != 0

- name: Get join token from manager
  hosts: manager
  tags: swram
  become: yes
  vars_files:
    - vars/swarm.yml
  tasks:
    - name: Get worker join token
      command: docker swarm join-token -q worker
      register: worker_token

    - name: Add token as a global host var
      add_host:
        name: swarm_token_holder
        swarm_join_token_global: "{{ worker_token.stdout }}"


- name: Join Worker to Swarm (CLI version)
  hosts: worker
  tags: swram
  become: yes
  vars_files:
    - vars/swarm.yml
  tasks:
    - name: Check if node is already in swarm
      command: docker info --format '{{ '{{.Swarm.LocalNodeState}}' }}'
      register: node_swarm_status
      changed_when: false
      ignore_errors: yes

    
    - name: Join the swarm as a worker
      command: >
        docker swarm join
        --token {{ hostvars['swarm_token_holder']['swarm_join_token_global'] }}
        --advertise-addr {{ worker_ip }}
        {{ manager_ip }}:2377
      when: node_swarm_status.stdout != "active" or node_swarm_status.rc != 0