---
- name: Install system dependencies
  hosts: all
  become: true
  gather_facts: false
  roles:
    - robertdebock.bootstrap

- name: Install Docker
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - vars/docker.yaml
  roles:
    - geerlingguy.docker

- name: Initialize Docker Swarm on Manager (CLI version)
  hosts: manager
  become: true
  vars_files:
    - vars/swarm.yaml
  tasks:
    - name: Check if swarm already initialized
      ansible.builtin.command: docker info --format '{{ '{{.Swarm.LocalNodeState}}' }}'
      register: swarm_status
      changed_when: false
      ignore_errors: true

    - name: Init Swarm if not already initialized
      ansible.builtin.command: docker swarm init --advertise-addr {{ manager_ip }}
      when: swarm_status.stdout != "active" or swarm_status.rc != 0
      changed_when: false

- name: Get join token from manager
  hosts: manager
  tags: swram
  become: true
  vars_files:
    - vars/swarm.yaml
  tasks:
    - name: Get worker join token
      ansible.builtin.command: docker swarm join-token -q worker
      register: worker_token
      changed_when: false

    - name: Add token as a global host var
      ansible.builtin.add_host:
        name: swarm_token_holder
        swarm_join_token_global: "{{ worker_token.stdout }}"


- name: Join Worker to Swarm (CLI version)
  hosts: worker
  tags: swram
  become: true
  vars_files:
    - vars/swarm.yaml
  tasks:
    - name: Check if node is already in swarm
      ansible.builtin.command: docker info --format '{{ '{{.Swarm.LocalNodeState}}' }}'
      register: node_swarm_status
      changed_when: false
      ignore_errors: true

    - name: Join the swarm as a worker
      ansible.builtin.command: >
        docker swarm join
        --token {{ hostvars['swarm_token_holder']['swarm_join_token_global'] }}
        --advertise-addr {{ worker_ip }}
        {{ manager_ip }}:2377
      when: node_swarm_status.stdout != "active" or node_swarm_status.rc != 0
      changed_when: false

- name: Copy docker-compose.yaml to Swarm Manager
  hosts: manager
  become: true
  vars_files:
    - vars/swarm.yaml
  tasks:
    - name: Copy docker-compose.yml into manager home
      ansible.builtin.copy:
        src: ../docker-compose.yml
        dest: /home/{{ ansible_user }}/docker-compose.yml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
