
# Install roles before run playbook for the depency
# ansible-galaxy install -r {file name} -p roles => to run the roles check  version
---
roles:
  - name: robertdebock.bootstrap
    src: robertdebock.bootstrap
  - name: geerlingguy.docker
    src: geerlingguy.docker