
# Install roles before run playbook for the depency
# ansible-galaxy role install -r {file name} to run the roles provide the path 
---
roles:
  - name: robertdebock.bootstrap
    src: robertdebock.bootstrap
  - name: geerlingguy.docker
    src: geerlingguy.docker